[package]
name = "adapter-markdown"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
adapter-rust = { workspace = true }
domain = { workspace = true }
ports = { workspace = true }
pulldown-cmark = { workspace = true }
regex = "1"
syn = { workspace = true }
walkdir = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
